#!/bin/fish
GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ CGO_CFLAGS="-I$PWD/win32_hidapi/include" CGO_LDFLAGS="-L$PWD/win32_hidapi/x64 -lhidapi" go build -ldflags "-s -w "
